version: '2'
run:
  tests: true
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
  exclusions:
    paths:
      - _templ\.go$
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
  exclusions:
    generated: lax
    paths:
      - _templ\.go$
output:
  formats:
    text:
      path: stdout
  sort-order:
    - linter
    - severity
    - file
