build:
  @templ generate
  @go build -o site-linux main.go
  @just build-tailwind

build-tailwind:
    @echo "Building Tailwind CSS..."
    @pnpm exec tailwindcss -i static/css/index.css -o static/css/out.css --content "./pages/**/*" --content "./layouts/**/*"
    @if [ -f static/css/out.css ]; then \
        HASH=$(sha256sum static/css/out.css | cut -d' ' -f1 | head -c8); \
        rm -f static/css/out.*.css; \
        cp static/css/out.css static/css/out.$HASH.css; \
        echo "Created static/css/out.$HASH.css"; \
    fi

watch:
  air

install:
  @pnpm install
  @go install github.com/air-verse/air@latest
  @go install github.com/a-h/templ/cmd/templ@latest
  @go get ./...
  @go mod tidy
  @go mod download

# Docker development commands
@up *args:
  just _compose local up '-d --build --remove-orphans' {{args}}
alias u := up

@down *args:
  just _compose local down {{args}}
alias d := down

# Generic Command
_compose environment cmd opts='' *args='':
  BUILDKIT_PROGRESS=plain \
  docker compose \
    -p creative-mode-site-{{environment}} \
    -f $(if [ '{{environment}}' = 'local' ]; then echo 'docker-compose.yml'; else echo "docker-compose.{{environment}}.yml"; fi) \
    {{cmd}} {{opts}} {{args}}

# Docker shell access
docker-shell service="app":
  @echo "Opening shell in {{service}} container..."
  just _compose local exec '' {{service}} sh

# Docker logs viewing
docker-tail service lines="50":
  @echo "Last {{lines}} lines for {{service}} service..."
  @docker logs --tail {{lines}} creative-mode-site-local-{{service}}-1
