check:
  @golangci-lint run ./...

build:
  @templ generate
  @go build -o site-linux main.go
  @just build-tailwind

build-tailwind:
    @echo "Building Tailwind CSS..."
    @pnpm exec tailwindcss -i static/css/index.css -o static/css/out.css --content "./pages/**/*" --content "./layouts/**/*"
    @if [ -f static/css/out.css ]; then \
        HASH=$(sha256sum static/css/out.css | cut -d' ' -f1 | head -c8); \
        rm -f static/css/out.*.css; \
        cp static/css/out.css static/css/out.$HASH.css; \
        echo "Created static/css/out.$HASH.css"; \
    fi

watch:
  air

install:
  @pnpm install
  @go install github.com/air-verse/air@latest
  @go install github.com/a-h/templ/cmd/templ@latest
  @go get ./...
  @go mod tidy
  @go mod download

up *args:
  BUILDKIT_PROGRESS=plain docker compose up -d --build --remove-orphans {{args}}
alias u := up

down *args:
  docker compose down {{args}}
alias d := down

logs service="app" lines="50":
  @docker logs --tail {{lines}} creative-mode-site-{{service}}-1

shell service="app":
  @docker compose exec {{service}} sh

# Production logs (systemd journal)
deploy-logs lines="100":
  journalctl -u creative-mode-site -n {{lines}} --no-pager
