-- Swarm task tracking
CREATE TABLE swarm_tasks (
    id TEXT PRIMARY KEY,
    primitive_type TEXT NOT NULL CHECK(primitive_type IN ('research', 'code_change_plan')),
    request_text TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK(status IN ('pending', 'running', 'completed', 'failed', 'canceled')),
    workflow_id TEXT,
    linear_issue_id TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Research sub-questions generated by the question-decomposition agent
CREATE TABLE swarm_research_questions (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL REFERENCES swarm_tasks(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    agent_index INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK(status IN ('pending', 'running', 'completed', 'failed')),
    result_summary TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Output artifacts (research docs, plan docs)
CREATE TABLE swarm_artifacts (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL REFERENCES swarm_tasks(id) ON DELETE CASCADE,
    artifact_type TEXT NOT NULL CHECK(artifact_type IN ('research_doc', 'plan_doc')),
    file_path TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Hierarchical span table (Langfuse-inspired trace/span model)
-- Each span has an optional parent, enabling tree views (nested agent → tool calls)
-- and timeline views (Gantt charts).
CREATE TABLE swarm_spans (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL REFERENCES swarm_tasks(id) ON DELETE CASCADE,
    parent_span_id TEXT REFERENCES swarm_spans(id),
    span_type TEXT NOT NULL CHECK(span_type IN (
        'workflow',      -- top-level: ResearchWorkflow or CodeChangePlanWorkflow
        'stage',         -- pipeline stage: question_generation, parallel_research, synthesis
        'agent',         -- single agent subprocess run
        'tool_call',     -- agent tool invocation (grep, read_file, ls, find)
        'llm_call',      -- LLM generation (if pi-mono exposes it)
        'question'       -- ask_orchestrator round-trip
    )),
    name TEXT NOT NULL,            -- e.g. "research-agent-0", "grep", "ask_orchestrator"
    status TEXT NOT NULL DEFAULT 'running'
        CHECK(status IN ('running', 'completed', 'failed')),
    input_json TEXT,               -- task input / tool args (truncated for large payloads)
    output_json TEXT,              -- artifact / tool result (truncated)
    error_message TEXT,            -- set on failure
    started_at TEXT NOT NULL,      -- set in Go code for ms precision (not SQLite default)
    ended_at TEXT,
    duration_ms INTEGER,           -- computed in Go: endedAt.Sub(startedAt).Milliseconds()
    metadata_json TEXT             -- extensible: model name, token counts, cost, agent_index, etc.
);

CREATE INDEX idx_swarm_tasks_status ON swarm_tasks(status);
CREATE INDEX idx_swarm_research_questions_task ON swarm_research_questions(task_id);
CREATE INDEX idx_swarm_artifacts_task ON swarm_artifacts(task_id);
CREATE INDEX idx_swarm_spans_task ON swarm_spans(task_id);
CREATE INDEX idx_swarm_spans_parent ON swarm_spans(parent_span_id);
CREATE INDEX idx_swarm_spans_started ON swarm_spans(started_at);
