root = "."
tmp_dir = "/tmp/air"

[build]
cmd = "templ generate && just build-tailwind && CGO_ENABLED=1 go build -o /tmp/harness ."
bin = "/tmp/harness"
include_ext = ["go", "templ", "css"]
exclude_regex = ["_templ\\.go$", "_test\\.go$", "out\\..*\\.css$", "out\\.css$"]
exclude_dir = ["data", "node_modules", "scripts"]
delay = 1000
poll = false
stop_on_error = false
send_interrupt = true
kill_delay = "3s"

[log]
time = false

[misc]
clean_on_exit = false
