default:
    @just --list

dev:
    go run .

build:
    go build -o harness .

test:
    go test ./...

sqlc:
    sqlc generate

generate:
    sqlc generate
    templ generate

fmt:
    golangci-lint fmt ./...

lint:
    golangci-lint run ./...
