// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkpoints.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countActiveBuilds = `-- name: CountActiveBuilds :one
SELECT COUNT(*) FROM checkpoints WHERE created_by = ? AND status = 'building'
`

func (q *Queries) CountActiveBuilds(ctx context.Context, createdBy sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveBuilds, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCheckpoint = `-- name: CreateCheckpoint :exec
INSERT INTO checkpoints (id, world_id, parent_checkpoint_id, name, prompt, status, dir_path, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCheckpointParams struct {
	ID                 string
	WorldID            string
	ParentCheckpointID sql.NullString
	Name               sql.NullString
	Prompt             sql.NullString
	Status             string
	DirPath            string
	CreatedBy          sql.NullString
}

func (q *Queries) CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, createCheckpoint,
		arg.ID,
		arg.WorldID,
		arg.ParentCheckpointID,
		arg.Name,
		arg.Prompt,
		arg.Status,
		arg.DirPath,
		arg.CreatedBy,
	)
	return err
}

const getCheckpoint = `-- name: GetCheckpoint :one
SELECT id, world_id, parent_checkpoint_id, name, prompt, status,
       build_log, work_summary, files_changed, build_duration_ms,
       dir_path, wasm_path, server_port, created_by, created_at
FROM checkpoints WHERE id = ?
`

func (q *Queries) GetCheckpoint(ctx context.Context, id string) (Checkpoint, error) {
	row := q.db.QueryRowContext(ctx, getCheckpoint, id)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.ParentCheckpointID,
		&i.Name,
		&i.Prompt,
		&i.Status,
		&i.BuildLog,
		&i.WorkSummary,
		&i.FilesChanged,
		&i.BuildDurationMs,
		&i.DirPath,
		&i.WasmPath,
		&i.ServerPort,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCheckpointTree = `-- name: GetCheckpointTree :many
SELECT id, world_id, parent_checkpoint_id, name, prompt, status,
       build_log, work_summary, files_changed, build_duration_ms,
       dir_path, wasm_path, server_port, created_by, created_at
FROM checkpoints WHERE world_id = ? ORDER BY created_at ASC
`

func (q *Queries) GetCheckpointTree(ctx context.Context, worldID string) ([]Checkpoint, error) {
	rows, err := q.db.QueryContext(ctx, getCheckpointTree, worldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkpoint{}
	for rows.Next() {
		var i Checkpoint
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.ParentCheckpointID,
			&i.Name,
			&i.Prompt,
			&i.Status,
			&i.BuildLog,
			&i.WorkSummary,
			&i.FilesChanged,
			&i.BuildDurationMs,
			&i.DirPath,
			&i.WasmPath,
			&i.ServerPort,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckpointDirPath = `-- name: UpdateCheckpointDirPath :exec
UPDATE checkpoints SET dir_path = ? WHERE id = ?
`

type UpdateCheckpointDirPathParams struct {
	DirPath string
	ID      string
}

func (q *Queries) UpdateCheckpointDirPath(ctx context.Context, arg UpdateCheckpointDirPathParams) error {
	_, err := q.db.ExecContext(ctx, updateCheckpointDirPath, arg.DirPath, arg.ID)
	return err
}

const updateCheckpointName = `-- name: UpdateCheckpointName :exec
UPDATE checkpoints SET name = ? WHERE id = ?
`

type UpdateCheckpointNameParams struct {
	Name sql.NullString
	ID   string
}

func (q *Queries) UpdateCheckpointName(ctx context.Context, arg UpdateCheckpointNameParams) error {
	_, err := q.db.ExecContext(ctx, updateCheckpointName, arg.Name, arg.ID)
	return err
}

const updateCheckpointServerPort = `-- name: UpdateCheckpointServerPort :execresult
UPDATE checkpoints SET server_port = ? WHERE id = ?
`

type UpdateCheckpointServerPortParams struct {
	ServerPort sql.NullInt64
	ID         string
}

func (q *Queries) UpdateCheckpointServerPort(ctx context.Context, arg UpdateCheckpointServerPortParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCheckpointServerPort, arg.ServerPort, arg.ID)
}

const updateCheckpointStatus = `-- name: UpdateCheckpointStatus :execresult
UPDATE checkpoints SET status = ?, build_log = ? WHERE id = ?
`

type UpdateCheckpointStatusParams struct {
	Status   string
	BuildLog sql.NullString
	ID       string
}

func (q *Queries) UpdateCheckpointStatus(ctx context.Context, arg UpdateCheckpointStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCheckpointStatus, arg.Status, arg.BuildLog, arg.ID)
}

const updateCheckpointSummary = `-- name: UpdateCheckpointSummary :execresult
UPDATE checkpoints SET work_summary = ?, files_changed = ?, build_duration_ms = ? WHERE id = ?
`

type UpdateCheckpointSummaryParams struct {
	WorkSummary     sql.NullString
	FilesChanged    sql.NullString
	BuildDurationMs sql.NullInt64
	ID              string
}

func (q *Queries) UpdateCheckpointSummary(ctx context.Context, arg UpdateCheckpointSummaryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCheckpointSummary,
		arg.WorkSummary,
		arg.FilesChanged,
		arg.BuildDurationMs,
		arg.ID,
	)
}

const updateCheckpointWasmPath = `-- name: UpdateCheckpointWasmPath :exec
UPDATE checkpoints SET wasm_path = ? WHERE id = ?
`

type UpdateCheckpointWasmPathParams struct {
	WasmPath sql.NullString
	ID       string
}

func (q *Queries) UpdateCheckpointWasmPath(ctx context.Context, arg UpdateCheckpointWasmPathParams) error {
	_, err := q.db.ExecContext(ctx, updateCheckpointWasmPath, arg.WasmPath, arg.ID)
	return err
}
