// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mayor_activity.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createMayorActivity = `-- name: CreateMayorActivity :exec
INSERT INTO mayor_activity (id, world_id, activity_type, detail)
VALUES (?, ?, ?, ?)
`

type CreateMayorActivityParams struct {
	ID           string
	WorldID      string
	ActivityType string
	Detail       sql.NullString
}

func (q *Queries) CreateMayorActivity(ctx context.Context, arg CreateMayorActivityParams) error {
	_, err := q.db.ExecContext(ctx, createMayorActivity,
		arg.ID,
		arg.WorldID,
		arg.ActivityType,
		arg.Detail,
	)
	return err
}

const getMayorActivity = `-- name: GetMayorActivity :many
SELECT id, world_id, activity_type, detail, created_at
FROM mayor_activity WHERE world_id = ? ORDER BY created_at DESC LIMIT ?
`

type GetMayorActivityParams struct {
	WorldID string
	Limit   int64
}

func (q *Queries) GetMayorActivity(ctx context.Context, arg GetMayorActivityParams) ([]MayorActivity, error) {
	rows, err := q.db.QueryContext(ctx, getMayorActivity, arg.WorldID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MayorActivity{}
	for rows.Next() {
		var i MayorActivity
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.ActivityType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMayorActivityAllWorlds = `-- name: GetRecentMayorActivityAllWorlds :many
SELECT id, world_id, activity_type, detail, created_at
FROM mayor_activity ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) GetRecentMayorActivityAllWorlds(ctx context.Context, limit int64) ([]MayorActivity, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMayorActivityAllWorlds, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MayorActivity{}
	for rows.Next() {
		var i MayorActivity
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.ActivityType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
