// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mayor_builds.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createMayorBuild = `-- name: CreateMayorBuild :exec
INSERT INTO mayor_builds (id, world_id, checkpoint_id, prompt, status)
VALUES (?, ?, ?, ?, ?)
`

type CreateMayorBuildParams struct {
	ID           string
	WorldID      string
	CheckpointID sql.NullString
	Prompt       string
	Status       string
}

func (q *Queries) CreateMayorBuild(ctx context.Context, arg CreateMayorBuildParams) error {
	_, err := q.db.ExecContext(ctx, createMayorBuild,
		arg.ID,
		arg.WorldID,
		arg.CheckpointID,
		arg.Prompt,
		arg.Status,
	)
	return err
}

const getMayorBuilds = `-- name: GetMayorBuilds :many
SELECT id, world_id, checkpoint_id, prompt, status, started_at, completed_at, duration_seconds, error_message
FROM mayor_builds WHERE world_id = ? ORDER BY started_at DESC LIMIT ?
`

type GetMayorBuildsParams struct {
	WorldID string
	Limit   int64
}

func (q *Queries) GetMayorBuilds(ctx context.Context, arg GetMayorBuildsParams) ([]MayorBuild, error) {
	rows, err := q.db.QueryContext(ctx, getMayorBuilds, arg.WorldID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MayorBuild{}
	for rows.Next() {
		var i MayorBuild
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.CheckpointID,
			&i.Prompt,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationSeconds,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMayorBuildsAllWorlds = `-- name: GetRecentMayorBuildsAllWorlds :many
SELECT id, world_id, checkpoint_id, prompt, status, started_at, completed_at, duration_seconds, error_message
FROM mayor_builds ORDER BY started_at DESC LIMIT ?
`

func (q *Queries) GetRecentMayorBuildsAllWorlds(ctx context.Context, limit int64) ([]MayorBuild, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMayorBuildsAllWorlds, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MayorBuild{}
	for rows.Next() {
		var i MayorBuild
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.CheckpointID,
			&i.Prompt,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationSeconds,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMayorBuildStatus = `-- name: UpdateMayorBuildStatus :exec
UPDATE mayor_builds
SET status = ?, completed_at = CURRENT_TIMESTAMP,
    duration_seconds = CAST((julianday(CURRENT_TIMESTAMP) - julianday(started_at)) * 86400 AS INTEGER),
    error_message = ?
WHERE id = ?
`

type UpdateMayorBuildStatusParams struct {
	Status       string
	ErrorMessage sql.NullString
	ID           string
}

func (q *Queries) UpdateMayorBuildStatus(ctx context.Context, arg UpdateMayorBuildStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMayorBuildStatus, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}
