// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mayor_messages.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createMayorMessage = `-- name: CreateMayorMessage :exec
INSERT INTO mayor_messages (id, world_id, discord_message_id, author_type, author_name, content)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMayorMessageParams struct {
	ID               string
	WorldID          string
	DiscordMessageID sql.NullString
	AuthorType       string
	AuthorName       string
	Content          string
}

func (q *Queries) CreateMayorMessage(ctx context.Context, arg CreateMayorMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMayorMessage,
		arg.ID,
		arg.WorldID,
		arg.DiscordMessageID,
		arg.AuthorType,
		arg.AuthorName,
		arg.Content,
	)
	return err
}

const getMayorMessageByDiscordID = `-- name: GetMayorMessageByDiscordID :one
SELECT id, world_id, discord_message_id, author_type, author_name, content, created_at
FROM mayor_messages WHERE discord_message_id = ?
`

func (q *Queries) GetMayorMessageByDiscordID(ctx context.Context, discordMessageID sql.NullString) (MayorMessage, error) {
	row := q.db.QueryRowContext(ctx, getMayorMessageByDiscordID, discordMessageID)
	var i MayorMessage
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.DiscordMessageID,
		&i.AuthorType,
		&i.AuthorName,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMayorMessages = `-- name: GetMayorMessages :many
SELECT id, world_id, discord_message_id, author_type, author_name, content, created_at
FROM mayor_messages WHERE world_id = ? ORDER BY created_at ASC
`

func (q *Queries) GetMayorMessages(ctx context.Context, worldID string) ([]MayorMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMayorMessages, worldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MayorMessage{}
	for rows.Next() {
		var i MayorMessage
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.DiscordMessageID,
			&i.AuthorType,
			&i.AuthorName,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMayorMessages = `-- name: GetRecentMayorMessages :many
SELECT id, world_id, discord_message_id, author_type, author_name, content, created_at
FROM mayor_messages WHERE world_id = ? ORDER BY created_at DESC LIMIT ?
`

type GetRecentMayorMessagesParams struct {
	WorldID string
	Limit   int64
}

func (q *Queries) GetRecentMayorMessages(ctx context.Context, arg GetRecentMayorMessagesParams) ([]MayorMessage, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMayorMessages, arg.WorldID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MayorMessage{}
	for rows.Next() {
		var i MayorMessage
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.DiscordMessageID,
			&i.AuthorType,
			&i.AuthorName,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
