// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (id, type, user_id, world_id, checkpoint_id, content)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ID           string
	Type         string
	UserID       sql.NullString
	WorldID      sql.NullString
	CheckpointID sql.NullString
	Content      string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.Type,
		arg.UserID,
		arg.WorldID,
		arg.CheckpointID,
		arg.Content,
	)
	return err
}

const getRecentMessages = `-- name: GetRecentMessages :many
SELECT id, type, user_id, world_id, checkpoint_id, content, created_at
FROM messages ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) GetRecentMessages(ctx context.Context, limit int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.UserID,
			&i.WorldID,
			&i.CheckpointID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMessagesByWorld = `-- name: GetRecentMessagesByWorld :many
SELECT id, type, user_id, world_id, checkpoint_id, content, created_at
FROM messages WHERE world_id = ? ORDER BY created_at DESC LIMIT ?
`

type GetRecentMessagesByWorldParams struct {
	WorldID sql.NullString
	Limit   int64
}

func (q *Queries) GetRecentMessagesByWorld(ctx context.Context, arg GetRecentMessagesByWorldParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMessagesByWorld, arg.WorldID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.UserID,
			&i.WorldID,
			&i.CheckpointID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
