// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Checkpoint struct {
	ID                 string
	WorldID            string
	ParentCheckpointID sql.NullString
	Name               sql.NullString
	Prompt             sql.NullString
	Status             string
	BuildLog           sql.NullString
	WorkSummary        sql.NullString
	FilesChanged       sql.NullString
	BuildDurationMs    sql.NullInt64
	DirPath            string
	WasmPath           sql.NullString
	ServerPort         sql.NullInt64
	CreatedBy          sql.NullString
	CreatedAt          time.Time
}

type MayorActivity struct {
	ID           string
	WorldID      string
	ActivityType string
	Detail       sql.NullString
	CreatedAt    time.Time
}

type MayorBuild struct {
	ID              string
	WorldID         string
	CheckpointID    sql.NullString
	Prompt          string
	Status          string
	StartedAt       time.Time
	CompletedAt     sql.NullTime
	DurationSeconds sql.NullInt64
	ErrorMessage    sql.NullString
}

type MayorMessage struct {
	ID               string
	WorldID          string
	DiscordMessageID sql.NullString
	AuthorType       string
	AuthorName       string
	Content          string
	CreatedAt        time.Time
}

type MayorSession struct {
	ID           string
	WorldID      string
	SessionKey   string
	MessageCount sql.NullInt64
	FirstSeenAt  time.Time
	LastActiveAt time.Time
}

type Message struct {
	ID           string
	Type         string
	UserID       sql.NullString
	WorldID      sql.NullString
	CheckpointID sql.NullString
	Content      string
	CreatedAt    time.Time
}

type PromptHistory struct {
	ID           string
	CheckpointID string
	WorldID      string
	UserID       string
	PromptText   string
	CreatedAt    time.Time
}

type Session struct {
	ID        string
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type SwarmArtifact struct {
	ID           string
	TaskID       string
	ArtifactType string
	FilePath     string
	CreatedAt    string
}

type SwarmResearchQuestion struct {
	ID            string
	TaskID        string
	QuestionText  string
	AgentIndex    int64
	Status        string
	ResultSummary sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

type SwarmSpan struct {
	ID           string
	TaskID       string
	ParentSpanID sql.NullString
	SpanType     string
	Name         string
	Status       string
	InputJSON    sql.NullString
	OutputJSON   sql.NullString
	ErrorMessage sql.NullString
	StartedAt    string
	EndedAt      sql.NullString
	DurationMs   sql.NullInt64
	MetadataJSON sql.NullString
}

type SwarmTask struct {
	ID            string
	PrimitiveType string
	RequestText   string
	Status        string
	WorkflowID    sql.NullString
	LinearIssueID sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

type User struct {
	ID              string
	DiscordID       string
	DiscordUsername string
	GitHubID        sql.NullInt64
	GitHubUsername  sql.NullString
	AvatarURL       sql.NullString
	Role            string
	CreatedAt       time.Time
	LastSeenAt      time.Time
}

type UserPosition struct {
	UserID         string
	WorldID        string
	CheckpointID   string
	LastAccessedAt time.Time
}

type World struct {
	ID               string
	Name             string
	Description      sql.NullString
	CreatedBy        sql.NullString
	CreatedAt        time.Time
	TemplateType     string
	MayorName        sql.NullString
	MayorPersonality sql.NullString
	MayorSecret      sql.NullString
	DiscordChannelID sql.NullString
	OpenClawAgentID  sql.NullString
	CoverImagePath   sql.NullString
}

type WorldInvite struct {
	WorldID   string
	UserID    string
	InvitedBy string
	CreatedAt time.Time
}
