// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: prompt_history.sql

package sqlc

import (
	"context"
)

const createPromptHistory = `-- name: CreatePromptHistory :exec
INSERT INTO prompt_history (id, checkpoint_id, world_id, user_id, prompt_text)
VALUES (?, ?, ?, ?, ?)
`

type CreatePromptHistoryParams struct {
	ID           string
	CheckpointID string
	WorldID      string
	UserID       string
	PromptText   string
}

func (q *Queries) CreatePromptHistory(ctx context.Context, arg CreatePromptHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createPromptHistory,
		arg.ID,
		arg.CheckpointID,
		arg.WorldID,
		arg.UserID,
		arg.PromptText,
	)
	return err
}
