// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	ArchiveOldLowRelevanceLearnings(ctx context.Context) error
	ArchiveSwarmLearning(ctx context.Context, id string) error
	ClearSwarmWorkflowGate(ctx context.Context, id string) error
	CompleteSwarmSession(ctx context.Context, arg CompleteSwarmSessionParams) error
	CompleteSwarmSessionWithTokens(ctx context.Context, arg CompleteSwarmSessionWithTokensParams) error
	CountActiveBuilds(ctx context.Context, createdBy sql.NullString) (int64, error)
	CountActiveSwarmSessions(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) error
	CreateMayorActivity(ctx context.Context, arg CreateMayorActivityParams) error
	CreateMayorBuild(ctx context.Context, arg CreateMayorBuildParams) error
	CreateMayorMessage(ctx context.Context, arg CreateMayorMessageParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	CreatePromptHistory(ctx context.Context, arg CreatePromptHistoryParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateSwarmDependency(ctx context.Context, arg CreateSwarmDependencyParams) error
	// swarm_events
	CreateSwarmEvent(ctx context.Context, arg CreateSwarmEventParams) error
	CreateSwarmGateReview(ctx context.Context, arg CreateSwarmGateReviewParams) error
	// swarm_learnings
	CreateSwarmLearning(ctx context.Context, arg CreateSwarmLearningParams) error
	// swarm_learning_digests
	CreateSwarmLearningDigest(ctx context.Context, arg CreateSwarmLearningDigestParams) error
	// swarm_project_milestones
	CreateSwarmMilestone(ctx context.Context, arg CreateSwarmMilestoneParams) error
	// swarm_sessions
	CreateSwarmSession(ctx context.Context, arg CreateSwarmSessionParams) error
	// swarm_workflows
	CreateSwarmWorkflow(ctx context.Context, arg CreateSwarmWorkflowParams) error
	CreateWorld(ctx context.Context, arg CreateWorldParams) error
	CreateWorldInvite(ctx context.Context, arg CreateWorldInviteParams) error
	DecaySwarmLearningRelevance(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteMessagesByUserID(ctx context.Context, userID sql.NullString) error
	DeletePromptHistoryByUserID(ctx context.Context, userID string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionsByUserID(ctx context.Context, userID string) error
	DeleteSwarmDependenciesByProject(ctx context.Context, projectID string) error
	DeleteSwarmTicketsByProject(ctx context.Context, projectID sql.NullString) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserPositionsByUserID(ctx context.Context, userID string) error
	DeleteWorldInvite(ctx context.Context, arg DeleteWorldInviteParams) error
	GetCheckpoint(ctx context.Context, id string) (Checkpoint, error)
	GetCheckpointTree(ctx context.Context, worldID string) ([]Checkpoint, error)
	GetLatestSwarmLearningDigest(ctx context.Context) (SwarmLearningDigest, error)
	GetLatestSwarmResultComment(ctx context.Context, ticketID string) (SwarmTicketComment, error)
	GetLatestSwarmSession(ctx context.Context, workflowID string) (GetLatestSwarmSessionRow, error)
	GetMayorActivity(ctx context.Context, arg GetMayorActivityParams) ([]MayorActivity, error)
	GetMayorBuilds(ctx context.Context, arg GetMayorBuildsParams) ([]MayorBuild, error)
	GetMayorMessageByDiscordID(ctx context.Context, discordMessageID sql.NullString) (MayorMessage, error)
	GetMayorMessages(ctx context.Context, worldID string) ([]MayorMessage, error)
	GetMayorSessions(ctx context.Context, arg GetMayorSessionsParams) ([]MayorSession, error)
	GetRecentMayorActivityAllWorlds(ctx context.Context, limit int64) ([]MayorActivity, error)
	GetRecentMayorBuildsAllWorlds(ctx context.Context, limit int64) ([]MayorBuild, error)
	GetRecentMayorMessages(ctx context.Context, arg GetRecentMayorMessagesParams) ([]MayorMessage, error)
	GetRecentMessagesByWorld(ctx context.Context, arg GetRecentMessagesByWorldParams) ([]Message, error)
	GetRecentMessagesWithUser(ctx context.Context, limit int64) ([]GetRecentMessagesWithUserRow, error)
	GetSession(ctx context.Context, id string) (Session, error)
	// swarm_config
	GetSwarmConfig(ctx context.Context) (SwarmConfig, error)
	GetSwarmLearning(ctx context.Context, id string) (SwarmLearning, error)
	GetSwarmMilestone(ctx context.Context, id string) (SwarmProjectMilestone, error)
	GetSwarmPromptVersion(ctx context.Context, id string) (SwarmPromptVersion, error)
	GetSwarmSession(ctx context.Context, id string) (GetSwarmSessionRow, error)
	GetSwarmTicket(ctx context.Context, id string) (SwarmTicket, error)
	GetSwarmTicketByIdentifier(ctx context.Context, identifier string) (SwarmTicket, error)
	GetSwarmWorkflow(ctx context.Context, id string) (SwarmWorkflow, error)
	GetSwarmWorkflowByPrevious(ctx context.Context, previousWorkflowID sql.NullString) (SwarmWorkflow, error)
	GetSwarmWorkflowsByTicket(ctx context.Context, ticketID string) ([]SwarmWorkflow, error)
	GetUserByDiscordID(ctx context.Context, discordID string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserPosition(ctx context.Context, arg GetUserPositionParams) (string, error)
	GetWorld(ctx context.Context, id string) (World, error)
	GetWorldByDiscordChannel(ctx context.Context, discordChannelID sql.NullString) (World, error)
	GetWorldByMayorSecret(ctx context.Context, mayorSecret sql.NullString) (World, error)
	GetWorldInvites(ctx context.Context, worldID string) ([]WorldInvite, error)
	GetWorldsWithDiscordChannels(ctx context.Context) ([]World, error)
	IncrementSwarmLearningReference(ctx context.Context, id string) error
	ListActiveSwarmWorkflows(ctx context.Context) ([]SwarmWorkflow, error)
	ListAllSwarmWorkflows(ctx context.Context, limit int64) ([]ListAllSwarmWorkflowsRow, error)
	ListAwaitingReviewSwarmWorkflows(ctx context.Context) ([]SwarmWorkflow, error)
	ListPendingUsers(ctx context.Context) ([]User, error)
	ListRecentSwarmEvents(ctx context.Context, limit int64) ([]SwarmEvent, error)
	ListRecentSwarmLearnings(ctx context.Context, createdAt string) ([]SwarmLearning, error)
	ListRunningSwarmWorkflows(ctx context.Context) ([]SwarmWorkflow, error)
	ListSwarmDependenciesByProject(ctx context.Context, projectID string) ([]SwarmTicketDependency, error)
	ListSwarmDependenciesByTicket(ctx context.Context, ticketID string) ([]SwarmTicketDependency, error)
	ListSwarmEventsByType(ctx context.Context, arg ListSwarmEventsByTypeParams) ([]SwarmEvent, error)
	ListSwarmEventsByWorkflow(ctx context.Context, workflowID sql.NullString) ([]SwarmEvent, error)
	ListSwarmGateReviewsByWorkflow(ctx context.Context, workflowID string) ([]ListSwarmGateReviewsByWorkflowRow, error)
	ListSwarmLearningDigests(ctx context.Context, limit int64) ([]SwarmLearningDigest, error)
	ListSwarmLearningsByTicket(ctx context.Context, ticketID string) ([]SwarmLearning, error)
	ListSwarmMilestonesByWorkflow(ctx context.Context, workflowID string) ([]SwarmProjectMilestone, error)
	ListSwarmSessionsByWorkflow(ctx context.Context, workflowID string) ([]ListSwarmSessionsByWorkflowRow, error)
	ListSwarmTicketComments(ctx context.Context, ticketID string) ([]SwarmTicketComment, error)
	ListSwarmTickets(ctx context.Context) ([]SwarmTicket, error)
	ListSwarmTicketsByParent(ctx context.Context, parentID sql.NullString) ([]SwarmTicket, error)
	ListSwarmTicketsByProject(ctx context.Context, projectID sql.NullString) ([]SwarmTicket, error)
	// Dashboard queries
	ListSwarmWorkflowsWithLatestSession(ctx context.Context) ([]ListSwarmWorkflowsWithLatestSessionRow, error)
	ListTopCriticalSwarmLearnings(ctx context.Context, limit int64) ([]SwarmLearning, error)
	ListTopSwarmLearningsByPhase(ctx context.Context, arg ListTopSwarmLearningsByPhaseParams) ([]SwarmLearning, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListWorlds(ctx context.Context) ([]World, error)
	SetUserPosition(ctx context.Context, arg SetUserPositionParams) error
	UpdateCheckpointDirPath(ctx context.Context, arg UpdateCheckpointDirPathParams) error
	UpdateCheckpointName(ctx context.Context, arg UpdateCheckpointNameParams) error
	UpdateCheckpointServerPort(ctx context.Context, arg UpdateCheckpointServerPortParams) (sql.Result, error)
	UpdateCheckpointStatus(ctx context.Context, arg UpdateCheckpointStatusParams) (sql.Result, error)
	UpdateCheckpointSummary(ctx context.Context, arg UpdateCheckpointSummaryParams) (sql.Result, error)
	UpdateCheckpointWasmPath(ctx context.Context, arg UpdateCheckpointWasmPathParams) error
	UpdateLastSeen(ctx context.Context, id string) error
	UpdateMayorBuildStatus(ctx context.Context, arg UpdateMayorBuildStatusParams) error
	UpdateSwarmConfig(ctx context.Context, config string) error
	UpdateSwarmMilestoneStatus(ctx context.Context, arg UpdateSwarmMilestoneStatusParams) error
	UpdateSwarmTicketDescription(ctx context.Context, arg UpdateSwarmTicketDescriptionParams) error
	UpdateSwarmWorkflowBranch(ctx context.Context, arg UpdateSwarmWorkflowBranchParams) error
	// Human gate queries
	UpdateSwarmWorkflowGate(ctx context.Context, arg UpdateSwarmWorkflowGateParams) error
	UpdateSwarmWorkflowLinearProject(ctx context.Context, arg UpdateSwarmWorkflowLinearProjectParams) error
	UpdateSwarmWorkflowPhase(ctx context.Context, arg UpdateSwarmWorkflowPhaseParams) error
	UpdateSwarmWorkflowReviewFeedback(ctx context.Context, arg UpdateSwarmWorkflowReviewFeedbackParams) error
	UpdateSwarmWorkflowStatus(ctx context.Context, arg UpdateSwarmWorkflowStatusParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (sql.Result, error)
	UpdateWorldCoverImage(ctx context.Context, arg UpdateWorldCoverImageParams) error
	UpdateWorldMayor(ctx context.Context, arg UpdateWorldMayorParams) error
	UpsertMayorSession(ctx context.Context, arg UpsertMayorSessionParams) error
	UpsertSwarmPromptVersion(ctx context.Context, arg UpsertSwarmPromptVersionParams) (string, error)
	// swarm_tickets
	UpsertSwarmTicket(ctx context.Context, arg UpsertSwarmTicketParams) error
	// swarm_ticket_comments
	UpsertSwarmTicketComment(ctx context.Context, arg UpsertSwarmTicketCommentParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
