// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Mark stale running spans as failed (e.g. after crash recovery).
	CleanupOrphanedSpans(ctx context.Context) error
	CompleteSwarmSpan(ctx context.Context, arg CompleteSwarmSpanParams) error
	CompleteSwarmSpanWithMetadata(ctx context.Context, arg CompleteSwarmSpanWithMetadataParams) error
	CountActiveBuilds(ctx context.Context, createdBy sql.NullString) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) error
	CreateMayorActivity(ctx context.Context, arg CreateMayorActivityParams) error
	CreateMayorBuild(ctx context.Context, arg CreateMayorBuildParams) error
	CreateMayorMessage(ctx context.Context, arg CreateMayorMessageParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	CreatePromptHistory(ctx context.Context, arg CreatePromptHistoryParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	// Swarm Artifacts
	CreateSwarmArtifact(ctx context.Context, arg CreateSwarmArtifactParams) error
	// Swarm Research Questions
	CreateSwarmResearchQuestion(ctx context.Context, arg CreateSwarmResearchQuestionParams) error
	// Swarm Spans
	CreateSwarmSpan(ctx context.Context, arg CreateSwarmSpanParams) error
	// Swarm Tasks
	CreateSwarmTask(ctx context.Context, arg CreateSwarmTaskParams) error
	// Swarm Task Messages
	CreateSwarmTaskMessage(ctx context.Context, arg CreateSwarmTaskMessageParams) error
	CreateWorld(ctx context.Context, arg CreateWorldParams) error
	CreateWorldInvite(ctx context.Context, arg CreateWorldInviteParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteMessagesByUserID(ctx context.Context, userID sql.NullString) error
	DeletePromptHistoryByUserID(ctx context.Context, userID string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionsByUserID(ctx context.Context, userID string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserPositionsByUserID(ctx context.Context, userID string) error
	DeleteWorldInvite(ctx context.Context, arg DeleteWorldInviteParams) error
	FailRunningSpansByTask(ctx context.Context, arg FailRunningSpansByTaskParams) error
	FailSwarmSpan(ctx context.Context, arg FailSwarmSpanParams) error
	FailSwarmSpanWithMetadata(ctx context.Context, arg FailSwarmSpanWithMetadataParams) error
	GetCheckpoint(ctx context.Context, id string) (Checkpoint, error)
	GetCheckpointTree(ctx context.Context, worldID string) ([]Checkpoint, error)
	GetMayorActivity(ctx context.Context, arg GetMayorActivityParams) ([]MayorActivity, error)
	GetMayorBuilds(ctx context.Context, arg GetMayorBuildsParams) ([]MayorBuild, error)
	GetMayorMessageByDiscordID(ctx context.Context, discordMessageID sql.NullString) (MayorMessage, error)
	GetMayorMessages(ctx context.Context, worldID string) ([]MayorMessage, error)
	GetMayorSessions(ctx context.Context, arg GetMayorSessionsParams) ([]MayorSession, error)
	GetRecentMayorActivityAllWorlds(ctx context.Context, limit int64) ([]MayorActivity, error)
	GetRecentMayorBuildsAllWorlds(ctx context.Context, limit int64) ([]MayorBuild, error)
	GetRecentMayorMessages(ctx context.Context, arg GetRecentMayorMessagesParams) ([]MayorMessage, error)
	GetRecentMessagesByWorld(ctx context.Context, arg GetRecentMessagesByWorldParams) ([]Message, error)
	GetRecentMessagesWithUser(ctx context.Context, limit int64) ([]GetRecentMessagesWithUserRow, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSwarmArtifact(ctx context.Context, id string) (SwarmArtifact, error)
	GetSwarmArtifactsByTask(ctx context.Context, taskID string) ([]SwarmArtifact, error)
	GetSwarmResearchQuestionsByTask(ctx context.Context, taskID string) ([]SwarmResearchQuestion, error)
	GetSwarmSpan(ctx context.Context, id string) (SwarmSpan, error)
	// Recursive CTE to get the full span tree for a task, ordered for tree rendering.
	// Returns spans depth-first: parent before children, siblings by start time.
	GetSwarmSpanTree(ctx context.Context, taskID string) ([]GetSwarmSpanTreeRow, error)
	GetSwarmSpansByTask(ctx context.Context, taskID string) ([]SwarmSpan, error)
	GetSwarmTask(ctx context.Context, id string) (SwarmTask, error)
	GetSwarmTaskMessages(ctx context.Context, taskID string) ([]SwarmTaskMessage, error)
	GetUserByDiscordID(ctx context.Context, discordID string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserPosition(ctx context.Context, arg GetUserPositionParams) (string, error)
	GetWorld(ctx context.Context, id string) (World, error)
	GetWorldByDiscordChannel(ctx context.Context, discordChannelID sql.NullString) (World, error)
	GetWorldByMayorSecret(ctx context.Context, mayorSecret sql.NullString) (World, error)
	GetWorldInvites(ctx context.Context, worldID string) ([]WorldInvite, error)
	GetWorldsWithDiscordChannels(ctx context.Context) ([]World, error)
	ListPendingUsers(ctx context.Context) ([]User, error)
	ListSwarmTasks(ctx context.Context, limit int64) ([]SwarmTask, error)
	ListSwarmTasksByStatus(ctx context.Context, arg ListSwarmTasksByStatusParams) ([]SwarmTask, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListWorlds(ctx context.Context) ([]World, error)
	SetUserPosition(ctx context.Context, arg SetUserPositionParams) error
	UpdateCheckpointDirPath(ctx context.Context, arg UpdateCheckpointDirPathParams) error
	UpdateCheckpointName(ctx context.Context, arg UpdateCheckpointNameParams) error
	UpdateCheckpointServerPort(ctx context.Context, arg UpdateCheckpointServerPortParams) (sql.Result, error)
	UpdateCheckpointStatus(ctx context.Context, arg UpdateCheckpointStatusParams) (sql.Result, error)
	UpdateCheckpointSummary(ctx context.Context, arg UpdateCheckpointSummaryParams) (sql.Result, error)
	UpdateCheckpointWasmPath(ctx context.Context, arg UpdateCheckpointWasmPathParams) error
	UpdateLastSeen(ctx context.Context, id string) error
	UpdateMayorBuildStatus(ctx context.Context, arg UpdateMayorBuildStatusParams) error
	UpdateSwarmResearchQuestion(ctx context.Context, arg UpdateSwarmResearchQuestionParams) error
	UpdateSwarmTaskStatus(ctx context.Context, arg UpdateSwarmTaskStatusParams) error
	UpdateSwarmTaskWorkflowID(ctx context.Context, arg UpdateSwarmTaskWorkflowIDParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (sql.Result, error)
	UpdateWorldCoverImage(ctx context.Context, arg UpdateWorldCoverImageParams) error
	UpdateWorldMayor(ctx context.Context, arg UpdateWorldMayorParams) error
	UpsertMayorSession(ctx context.Context, arg UpsertMayorSessionParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
