// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountActiveBuilds(ctx context.Context, createdBy sql.NullString) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) error
	CreateMayorActivity(ctx context.Context, arg CreateMayorActivityParams) error
	CreateMayorBuild(ctx context.Context, arg CreateMayorBuildParams) error
	CreateMayorMessage(ctx context.Context, arg CreateMayorMessageParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	CreatePromptHistory(ctx context.Context, arg CreatePromptHistoryParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateWorld(ctx context.Context, arg CreateWorldParams) error
	CreateWorldInvite(ctx context.Context, arg CreateWorldInviteParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteMessagesByUserID(ctx context.Context, userID sql.NullString) error
	DeletePromptHistoryByUserID(ctx context.Context, userID string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionsByUserID(ctx context.Context, userID string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserPositionsByUserID(ctx context.Context, userID string) error
	DeleteWorldInvite(ctx context.Context, arg DeleteWorldInviteParams) error
	GetCheckpoint(ctx context.Context, id string) (Checkpoint, error)
	GetCheckpointTree(ctx context.Context, worldID string) ([]Checkpoint, error)
	GetMayorActivity(ctx context.Context, arg GetMayorActivityParams) ([]MayorActivity, error)
	GetMayorBuilds(ctx context.Context, arg GetMayorBuildsParams) ([]MayorBuild, error)
	GetMayorMessageByDiscordID(ctx context.Context, discordMessageID sql.NullString) (MayorMessage, error)
	GetMayorMessages(ctx context.Context, worldID string) ([]MayorMessage, error)
	GetMayorSessions(ctx context.Context, arg GetMayorSessionsParams) ([]MayorSession, error)
	GetRecentMayorActivityAllWorlds(ctx context.Context, limit int64) ([]MayorActivity, error)
	GetRecentMayorBuildsAllWorlds(ctx context.Context, limit int64) ([]MayorBuild, error)
	GetRecentMayorMessages(ctx context.Context, arg GetRecentMayorMessagesParams) ([]MayorMessage, error)
	GetRecentMessagesByWorld(ctx context.Context, arg GetRecentMessagesByWorldParams) ([]Message, error)
	GetRecentMessagesWithUser(ctx context.Context, limit int64) ([]GetRecentMessagesWithUserRow, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetUserByDiscordID(ctx context.Context, discordID string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserPosition(ctx context.Context, arg GetUserPositionParams) (string, error)
	GetWorld(ctx context.Context, id string) (World, error)
	GetWorldByDiscordChannel(ctx context.Context, discordChannelID sql.NullString) (World, error)
	GetWorldByMayorSecret(ctx context.Context, mayorSecret sql.NullString) (World, error)
	GetWorldInvites(ctx context.Context, worldID string) ([]WorldInvite, error)
	GetWorldsWithDiscordChannels(ctx context.Context) ([]World, error)
	ListPendingUsers(ctx context.Context) ([]User, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListWorlds(ctx context.Context) ([]World, error)
	SetUserPosition(ctx context.Context, arg SetUserPositionParams) error
	UpdateCheckpointDirPath(ctx context.Context, arg UpdateCheckpointDirPathParams) error
	UpdateCheckpointName(ctx context.Context, arg UpdateCheckpointNameParams) error
	UpdateCheckpointServerPort(ctx context.Context, arg UpdateCheckpointServerPortParams) (sql.Result, error)
	UpdateCheckpointStatus(ctx context.Context, arg UpdateCheckpointStatusParams) (sql.Result, error)
	UpdateCheckpointSummary(ctx context.Context, arg UpdateCheckpointSummaryParams) (sql.Result, error)
	UpdateCheckpointWasmPath(ctx context.Context, arg UpdateCheckpointWasmPathParams) error
	UpdateLastSeen(ctx context.Context, id string) error
	UpdateMayorBuildStatus(ctx context.Context, arg UpdateMayorBuildStatusParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (sql.Result, error)
	UpdateWorldCoverImage(ctx context.Context, arg UpdateWorldCoverImageParams) error
	UpdateWorldMayor(ctx context.Context, arg UpdateWorldMayorParams) error
	UpsertMayorSession(ctx context.Context, arg UpsertMayorSessionParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
