// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: swarm_prompts.sql

package sqlc

import (
	"context"
)

const getSwarmPromptVersion = `-- name: GetSwarmPromptVersion :one
SELECT id, phase, content_hash, created_at
FROM swarm_prompt_versions WHERE id = ?
`

func (q *Queries) GetSwarmPromptVersion(ctx context.Context, id string) (SwarmPromptVersion, error) {
	row := q.db.QueryRowContext(ctx, getSwarmPromptVersion, id)
	var i SwarmPromptVersion
	err := row.Scan(
		&i.ID,
		&i.Phase,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSwarmPromptVersion = `-- name: UpsertSwarmPromptVersion :one
INSERT INTO swarm_prompt_versions (id, phase, content_hash)
VALUES (?, ?, ?)
ON CONFLICT(phase, content_hash) DO UPDATE SET id = swarm_prompt_versions.id
RETURNING id
`

type UpsertSwarmPromptVersionParams struct {
	ID          string
	Phase       string
	ContentHash string
}

func (q *Queries) UpsertSwarmPromptVersion(ctx context.Context, arg UpsertSwarmPromptVersionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertSwarmPromptVersion, arg.ID, arg.Phase, arg.ContentHash)
	var id string
	err := row.Scan(&id)
	return id, err
}
