// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: swarm_learnings.sql

package sqlc

import (
	"context"
	"database/sql"

	"creative-mode/harness/internal/swarm"
)

const archiveOldLowRelevanceLearnings = `-- name: ArchiveOldLowRelevanceLearnings :exec
UPDATE swarm_learnings
SET archived_at = datetime('now'), updated_at = datetime('now')
WHERE archived_at IS NULL
  AND relevance_score < 0.1
  AND created_at < datetime('now', '-60 days')
`

func (q *Queries) ArchiveOldLowRelevanceLearnings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, archiveOldLowRelevanceLearnings)
	return err
}

const archiveSwarmLearning = `-- name: ArchiveSwarmLearning :exec
UPDATE swarm_learnings SET archived_at = datetime('now'), updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) ArchiveSwarmLearning(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, archiveSwarmLearning, id)
	return err
}

const createSwarmLearning = `-- name: CreateSwarmLearning :exec

INSERT INTO swarm_learnings (id, source_workflow_id, source_session_id, ticket_id, category, phase, severity, title, content, doc_path, tags)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSwarmLearningParams struct {
	ID               string
	SourceWorkflowID sql.NullString
	SourceSessionID  sql.NullString
	TicketID         string
	Category         swarm.LearningCategory
	Phase            sql.NullString
	Severity         swarm.LearningSeverity
	Title            string
	Content          string
	DocPath          sql.NullString
	Tags             sql.NullString
}

// swarm_learnings
func (q *Queries) CreateSwarmLearning(ctx context.Context, arg CreateSwarmLearningParams) error {
	_, err := q.db.ExecContext(ctx, createSwarmLearning,
		arg.ID,
		arg.SourceWorkflowID,
		arg.SourceSessionID,
		arg.TicketID,
		arg.Category,
		arg.Phase,
		arg.Severity,
		arg.Title,
		arg.Content,
		arg.DocPath,
		arg.Tags,
	)
	return err
}

const createSwarmLearningDigest = `-- name: CreateSwarmLearningDigest :exec

INSERT INTO swarm_learning_digests (id, digest_type, period_start, period_end, learning_count, summary, action_items, doc_path)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSwarmLearningDigestParams struct {
	ID            string
	DigestType    string
	PeriodStart   string
	PeriodEnd     string
	LearningCount int64
	Summary       string
	ActionItems   sql.NullString
	DocPath       sql.NullString
}

// swarm_learning_digests
func (q *Queries) CreateSwarmLearningDigest(ctx context.Context, arg CreateSwarmLearningDigestParams) error {
	_, err := q.db.ExecContext(ctx, createSwarmLearningDigest,
		arg.ID,
		arg.DigestType,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.LearningCount,
		arg.Summary,
		arg.ActionItems,
		arg.DocPath,
	)
	return err
}

const decaySwarmLearningRelevance = `-- name: DecaySwarmLearningRelevance :exec
UPDATE swarm_learnings
SET relevance_score = relevance_score * 0.95, updated_at = datetime('now')
WHERE archived_at IS NULL AND relevance_score > 0.1
`

func (q *Queries) DecaySwarmLearningRelevance(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, decaySwarmLearningRelevance)
	return err
}

const getLatestSwarmLearningDigest = `-- name: GetLatestSwarmLearningDigest :one
SELECT id, digest_type, period_start, period_end, learning_count, summary, action_items, doc_path, created_at
FROM swarm_learning_digests ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestSwarmLearningDigest(ctx context.Context) (SwarmLearningDigest, error) {
	row := q.db.QueryRowContext(ctx, getLatestSwarmLearningDigest)
	var i SwarmLearningDigest
	err := row.Scan(
		&i.ID,
		&i.DigestType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.LearningCount,
		&i.Summary,
		&i.ActionItems,
		&i.DocPath,
		&i.CreatedAt,
	)
	return i, err
}

const getSwarmLearning = `-- name: GetSwarmLearning :one
SELECT id, source_workflow_id, source_session_id, ticket_id, category, phase, severity, title, content, doc_path, tags, relevance_score, referenced_count, archived_at, created_at, updated_at
FROM swarm_learnings WHERE id = ?
`

func (q *Queries) GetSwarmLearning(ctx context.Context, id string) (SwarmLearning, error) {
	row := q.db.QueryRowContext(ctx, getSwarmLearning, id)
	var i SwarmLearning
	err := row.Scan(
		&i.ID,
		&i.SourceWorkflowID,
		&i.SourceSessionID,
		&i.TicketID,
		&i.Category,
		&i.Phase,
		&i.Severity,
		&i.Title,
		&i.Content,
		&i.DocPath,
		&i.Tags,
		&i.RelevanceScore,
		&i.ReferencedCount,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementSwarmLearningReference = `-- name: IncrementSwarmLearningReference :exec
UPDATE swarm_learnings
SET referenced_count = referenced_count + 1, relevance_score = relevance_score + 0.1, updated_at = datetime('now')
WHERE id = ?
`

func (q *Queries) IncrementSwarmLearningReference(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementSwarmLearningReference, id)
	return err
}

const listRecentSwarmLearnings = `-- name: ListRecentSwarmLearnings :many
SELECT id, source_workflow_id, source_session_id, ticket_id, category, phase, severity, title, content, doc_path, tags, relevance_score, referenced_count, archived_at, created_at, updated_at
FROM swarm_learnings
WHERE archived_at IS NULL AND created_at > ?
ORDER BY created_at DESC
`

func (q *Queries) ListRecentSwarmLearnings(ctx context.Context, createdAt string) ([]SwarmLearning, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSwarmLearnings, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SwarmLearning{}
	for rows.Next() {
		var i SwarmLearning
		if err := rows.Scan(
			&i.ID,
			&i.SourceWorkflowID,
			&i.SourceSessionID,
			&i.TicketID,
			&i.Category,
			&i.Phase,
			&i.Severity,
			&i.Title,
			&i.Content,
			&i.DocPath,
			&i.Tags,
			&i.RelevanceScore,
			&i.ReferencedCount,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSwarmLearningDigests = `-- name: ListSwarmLearningDigests :many
SELECT id, digest_type, period_start, period_end, learning_count, summary, action_items, doc_path, created_at
FROM swarm_learning_digests ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListSwarmLearningDigests(ctx context.Context, limit int64) ([]SwarmLearningDigest, error) {
	rows, err := q.db.QueryContext(ctx, listSwarmLearningDigests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SwarmLearningDigest{}
	for rows.Next() {
		var i SwarmLearningDigest
		if err := rows.Scan(
			&i.ID,
			&i.DigestType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.LearningCount,
			&i.Summary,
			&i.ActionItems,
			&i.DocPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSwarmLearningsByTicket = `-- name: ListSwarmLearningsByTicket :many
SELECT id, source_workflow_id, source_session_id, ticket_id, category, phase, severity, title, content, doc_path, tags, relevance_score, referenced_count, archived_at, created_at, updated_at
FROM swarm_learnings WHERE ticket_id = ? AND archived_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListSwarmLearningsByTicket(ctx context.Context, ticketID string) ([]SwarmLearning, error) {
	rows, err := q.db.QueryContext(ctx, listSwarmLearningsByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SwarmLearning{}
	for rows.Next() {
		var i SwarmLearning
		if err := rows.Scan(
			&i.ID,
			&i.SourceWorkflowID,
			&i.SourceSessionID,
			&i.TicketID,
			&i.Category,
			&i.Phase,
			&i.Severity,
			&i.Title,
			&i.Content,
			&i.DocPath,
			&i.Tags,
			&i.RelevanceScore,
			&i.ReferencedCount,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopCriticalSwarmLearnings = `-- name: ListTopCriticalSwarmLearnings :many
SELECT id, source_workflow_id, source_session_id, ticket_id, category, phase, severity, title, content, doc_path, tags, relevance_score, referenced_count, archived_at, created_at, updated_at
FROM swarm_learnings
WHERE severity = 'critical' AND archived_at IS NULL
ORDER BY relevance_score DESC
LIMIT ?
`

func (q *Queries) ListTopCriticalSwarmLearnings(ctx context.Context, limit int64) ([]SwarmLearning, error) {
	rows, err := q.db.QueryContext(ctx, listTopCriticalSwarmLearnings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SwarmLearning{}
	for rows.Next() {
		var i SwarmLearning
		if err := rows.Scan(
			&i.ID,
			&i.SourceWorkflowID,
			&i.SourceSessionID,
			&i.TicketID,
			&i.Category,
			&i.Phase,
			&i.Severity,
			&i.Title,
			&i.Content,
			&i.DocPath,
			&i.Tags,
			&i.RelevanceScore,
			&i.ReferencedCount,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopSwarmLearningsByPhase = `-- name: ListTopSwarmLearningsByPhase :many
SELECT id, source_workflow_id, source_session_id, ticket_id, category, phase, severity, title, content, doc_path, tags, relevance_score, referenced_count, archived_at, created_at, updated_at
FROM swarm_learnings
WHERE phase = ? AND archived_at IS NULL
ORDER BY relevance_score DESC
LIMIT ?
`

type ListTopSwarmLearningsByPhaseParams struct {
	Phase sql.NullString
	Limit int64
}

func (q *Queries) ListTopSwarmLearningsByPhase(ctx context.Context, arg ListTopSwarmLearningsByPhaseParams) ([]SwarmLearning, error) {
	rows, err := q.db.QueryContext(ctx, listTopSwarmLearningsByPhase, arg.Phase, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SwarmLearning{}
	for rows.Next() {
		var i SwarmLearning
		if err := rows.Scan(
			&i.ID,
			&i.SourceWorkflowID,
			&i.SourceSessionID,
			&i.TicketID,
			&i.Category,
			&i.Phase,
			&i.Severity,
			&i.Title,
			&i.Content,
			&i.DocPath,
			&i.Tags,
			&i.RelevanceScore,
			&i.ReferencedCount,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
