// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: swarm_dependencies.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSwarmDependency = `-- name: CreateSwarmDependency :exec
INSERT INTO swarm_ticket_dependencies (id, ticket_id, depends_on_ticket_id, project_id)
VALUES (?, ?, ?, ?)
`

type CreateSwarmDependencyParams struct {
	ID                string
	TicketID          string
	DependsOnTicketID string
	ProjectID         string
}

func (q *Queries) CreateSwarmDependency(ctx context.Context, arg CreateSwarmDependencyParams) error {
	_, err := q.db.ExecContext(ctx, createSwarmDependency,
		arg.ID,
		arg.TicketID,
		arg.DependsOnTicketID,
		arg.ProjectID,
	)
	return err
}

const deleteSwarmDependenciesByProject = `-- name: DeleteSwarmDependenciesByProject :exec
DELETE FROM swarm_ticket_dependencies WHERE project_id = ?
`

func (q *Queries) DeleteSwarmDependenciesByProject(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteSwarmDependenciesByProject, projectID)
	return err
}

const listSwarmDependenciesByProject = `-- name: ListSwarmDependenciesByProject :many
SELECT id, ticket_id, depends_on_ticket_id, project_id, created_at
FROM swarm_ticket_dependencies
WHERE project_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListSwarmDependenciesByProject(ctx context.Context, projectID string) ([]SwarmTicketDependency, error) {
	rows, err := q.db.QueryContext(ctx, listSwarmDependenciesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SwarmTicketDependency{}
	for rows.Next() {
		var i SwarmTicketDependency
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.DependsOnTicketID,
			&i.ProjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSwarmDependenciesByTicket = `-- name: ListSwarmDependenciesByTicket :many
SELECT id, ticket_id, depends_on_ticket_id, project_id, created_at
FROM swarm_ticket_dependencies
WHERE ticket_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListSwarmDependenciesByTicket(ctx context.Context, ticketID string) ([]SwarmTicketDependency, error) {
	rows, err := q.db.QueryContext(ctx, listSwarmDependenciesByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SwarmTicketDependency{}
	for rows.Next() {
		var i SwarmTicketDependency
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.DependsOnTicketID,
			&i.ProjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSwarmTicketsByParent = `-- name: ListSwarmTicketsByParent :many
SELECT id, identifier, title, status, priority, assignee, labels, parent_id, project_id, url, created_at, updated_at, synced_at
FROM swarm_tickets
WHERE parent_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListSwarmTicketsByParent(ctx context.Context, parentID sql.NullString) ([]SwarmTicket, error) {
	rows, err := q.db.QueryContext(ctx, listSwarmTicketsByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SwarmTicket{}
	for rows.Next() {
		var i SwarmTicket
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Labels,
			&i.ParentID,
			&i.ProjectID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSwarmTicketsByProject = `-- name: ListSwarmTicketsByProject :many
SELECT id, identifier, title, status, priority, assignee, labels, parent_id, project_id, url, created_at, updated_at, synced_at
FROM swarm_tickets
WHERE project_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListSwarmTicketsByProject(ctx context.Context, projectID sql.NullString) ([]SwarmTicket, error) {
	rows, err := q.db.QueryContext(ctx, listSwarmTicketsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SwarmTicket{}
	for rows.Next() {
		var i SwarmTicket
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Labels,
			&i.ParentID,
			&i.ProjectID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
