// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: swarm_gate_reviews.sql

package sqlc

import (
	"context"
	"database/sql"

	"creative-mode/harness/internal/swarm"
)

const createSwarmGateReview = `-- name: CreateSwarmGateReview :exec
INSERT INTO swarm_gate_reviews (id, workflow_id, gate_phase, action, feedback, reviewer)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSwarmGateReviewParams struct {
	ID         string
	WorkflowID string
	GatePhase  swarm.Phase
	Action     string
	Feedback   sql.NullString
	Reviewer   sql.NullString
}

func (q *Queries) CreateSwarmGateReview(ctx context.Context, arg CreateSwarmGateReviewParams) error {
	_, err := q.db.ExecContext(ctx, createSwarmGateReview,
		arg.ID,
		arg.WorkflowID,
		arg.GatePhase,
		arg.Action,
		arg.Feedback,
		arg.Reviewer,
	)
	return err
}

const listSwarmGateReviewsByWorkflow = `-- name: ListSwarmGateReviewsByWorkflow :many
SELECT id, workflow_id, gate_phase, action, feedback, reviewer, created_at
FROM swarm_gate_reviews WHERE workflow_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListSwarmGateReviewsByWorkflow(ctx context.Context, workflowID string) ([]SwarmGateReview, error) {
	rows, err := q.db.QueryContext(ctx, listSwarmGateReviewsByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SwarmGateReview{}
	for rows.Next() {
		var i SwarmGateReview
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.GatePhase,
			&i.Action,
			&i.Feedback,
			&i.Reviewer,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
