// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByGitHubID = `-- name: GetUserByGitHubID :one
SELECT id, github_id, github_username, avatar_url, role, created_at, last_seen_at
FROM users WHERE github_id = ?
`

func (q *Queries) GetUserByGitHubID(ctx context.Context, githubID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGitHubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GitHubID,
		&i.GitHubUsername,
		&i.AvatarURL,
		&i.Role,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, github_username, avatar_url, role, created_at, last_seen_at
FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GitHubID,
		&i.GitHubUsername,
		&i.AvatarURL,
		&i.Role,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listPendingUsers = `-- name: ListPendingUsers :many
SELECT id, github_id, github_username, avatar_url, role, created_at, last_seen_at
FROM users WHERE role = 'pending' ORDER BY created_at ASC
`

func (q *Queries) ListPendingUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listPendingUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GitHubID,
			&i.GitHubUsername,
			&i.AvatarURL,
			&i.Role,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, github_id, github_username, avatar_url, role, created_at, last_seen_at
FROM users ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GitHubID,
			&i.GitHubUsername,
			&i.AvatarURL,
			&i.Role,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE users SET last_seen_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateLastSeen(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateLastSeen, id)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :execresult
UPDATE users SET role = ? WHERE id = ?
`

type UpdateUserRoleParams struct {
	Role string
	ID   string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, github_id, github_username, avatar_url, role)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(github_id) DO UPDATE SET
    github_username = excluded.github_username,
    avatar_url = excluded.avatar_url,
    last_seen_at = CURRENT_TIMESTAMP
`

type UpsertUserParams struct {
	ID             string
	GitHubID       int64
	GitHubUsername string
	AvatarURL      sql.NullString
	Role           string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.ID,
		arg.GitHubID,
		arg.GitHubUsername,
		arg.AvatarURL,
		arg.Role,
	)
	return err
}
