// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_positions.sql

package sqlc

import (
	"context"
)

const deleteUserPositionsByUserID = `-- name: DeleteUserPositionsByUserID :exec
DELETE FROM user_positions WHERE user_id = ?
`

func (q *Queries) DeleteUserPositionsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserPositionsByUserID, userID)
	return err
}

const getUserPosition = `-- name: GetUserPosition :one
SELECT checkpoint_id FROM user_positions
WHERE user_id = ? AND world_id = ?
`

type GetUserPositionParams struct {
	UserID  string
	WorldID string
}

func (q *Queries) GetUserPosition(ctx context.Context, arg GetUserPositionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPosition, arg.UserID, arg.WorldID)
	var checkpoint_id string
	err := row.Scan(&checkpoint_id)
	return checkpoint_id, err
}

const setUserPosition = `-- name: SetUserPosition :exec
INSERT INTO user_positions (user_id, world_id, checkpoint_id, last_accessed_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_id, world_id) DO UPDATE SET
    checkpoint_id = excluded.checkpoint_id,
    last_accessed_at = CURRENT_TIMESTAMP
`

type SetUserPositionParams struct {
	UserID       string
	WorldID      string
	CheckpointID string
}

func (q *Queries) SetUserPosition(ctx context.Context, arg SetUserPositionParams) error {
	_, err := q.db.ExecContext(ctx, setUserPosition, arg.UserID, arg.WorldID, arg.CheckpointID)
	return err
}
