// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByDiscordID = `-- name: GetUserByDiscordID :one
SELECT id, discord_id, discord_username, github_id, github_username, avatar_url, role, created_at, last_seen_at
FROM users WHERE discord_id = ?
`

func (q *Queries) GetUserByDiscordID(ctx context.Context, discordID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByDiscordID, discordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.GitHubID,
		&i.GitHubUsername,
		&i.AvatarURL,
		&i.Role,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, discord_id, discord_username, github_id, github_username, avatar_url, role, created_at, last_seen_at
FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.GitHubID,
		&i.GitHubUsername,
		&i.AvatarURL,
		&i.Role,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listPendingUsers = `-- name: ListPendingUsers :many
SELECT id, discord_id, discord_username, github_id, github_username, avatar_url, role, created_at, last_seen_at
FROM users WHERE role = 'pending' ORDER BY created_at ASC
`

func (q *Queries) ListPendingUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listPendingUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DiscordID,
			&i.DiscordUsername,
			&i.GitHubID,
			&i.GitHubUsername,
			&i.AvatarURL,
			&i.Role,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, discord_id, discord_username, github_id, github_username, avatar_url, role, created_at, last_seen_at
FROM users ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DiscordID,
			&i.DiscordUsername,
			&i.GitHubID,
			&i.GitHubUsername,
			&i.AvatarURL,
			&i.Role,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE users SET last_seen_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateLastSeen(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateLastSeen, id)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :execresult
UPDATE users SET role = ? WHERE id = ?
`

type UpdateUserRoleParams struct {
	Role UserRole
	ID   string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, discord_id, discord_username, avatar_url, role)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(discord_id) DO UPDATE SET
    discord_username = excluded.discord_username,
    avatar_url = excluded.avatar_url,
    last_seen_at = CURRENT_TIMESTAMP
`

type UpsertUserParams struct {
	ID              string
	DiscordID       string
	DiscordUsername string
	AvatarURL       sql.NullString
	Role            UserRole
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.ID,
		arg.DiscordID,
		arg.DiscordUsername,
		arg.AvatarURL,
		arg.Role,
	)
	return err
}
